//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lux_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lux_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string BtnDownload {
            get {
                return ResourceManager.GetString("BtnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析 的本地化字符串。
        /// </summary>
        public static string BtnParse {
            get {
                return ResourceManager.GetString("BtnParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放列表 的本地化字符串。
        /// </summary>
        public static string CbPlayLists {
            get {
                return ResourceManager.GetString("CbPlayLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流名称 的本地化字符串。
        /// </summary>
        public static string HName {
            get {
                return ResourceManager.GetString("HName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string HOperation {
            get {
                return ResourceManager.GetString("HOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质量 的本地化字符串。
        /// </summary>
        public static string HQuality {
            get {
                return ResourceManager.GetString("HQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        public static string HSize {
            get {
                return ResourceManager.GetString("HSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string HTitle {
            get {
                return ResourceManager.GetString("HTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附加参数 的本地化字符串。
        /// </summary>
        public static string LbAdditionalParameters {
            get {
                return ResourceManager.GetString("LbAdditionalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载地址 的本地化字符串。
        /// </summary>
        public static string LbDownloadURL {
            get {
                return ResourceManager.GetString("LbDownloadURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始集数 的本地化字符串。
        /// </summary>
        public static string LbFrom {
            get {
                return ResourceManager.GetString("LbFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流名称过滤 的本地化字符串。
        /// </summary>
        public static string LbNameFilter {
            get {
                return ResourceManager.GetString("LbNameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析资源中 的本地化字符串。
        /// </summary>
        public static string LbParsing {
            get {
                return ResourceManager.GetString("LbParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质量过滤 的本地化字符串。
        /// </summary>
        public static string LbQualityFilter {
            get {
                return ResourceManager.GetString("LbQualityFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选集 的本地化字符串。
        /// </summary>
        public static string LbSelect {
            get {
                return ResourceManager.GetString("LbSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束集数 的本地化字符串。
        /// </summary>
        public static string LbTo {
            get {
                return ResourceManager.GetString("LbTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string RbSelectAll {
            get {
                return ResourceManager.GetString("RbSelectAll", resourceCulture);
            }
        }
    }
}
